syntax on

set number "line numbers

set nowrap "do not wrap if content longer than terminal

set laststatus=2 "more infos in on the bottom vi status line

set paste "enable copy/paste

"set list "show whitespaces

" kudos to https://vim.fandom.com/wiki/Converting_tabs_to_spaces (2020-06-23T11:36:25 CEST)
set expandtab "insert space characters whenever the tab key is pressed
set tabstop=4 "control the number of space characters that will be inserted when the tab key is pressed
set shiftwidth=4 "change the number of space characters inserted for indentation
set softtabstop=4 "insert and delete the correct number of spaces
set smarttab "new tab characters entered will be changed to spaces. use :retab to convert existing tab characters

